"""init

Revision ID: 8588c32f2d59
Revises: 2b64ce963c1c
Create Date: 2020-10-15 09:19:21.972724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8588c32f2d59'
down_revision = '2b64ce963c1c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
