"""init

Revision ID: 54ea7ee520e2
Revises: 8588c32f2d59
Create Date: 2020-10-22 10:07:50.260386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ea7ee520e2'
down_revision = '8588c32f2d59'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loggedIn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loggedIn')
    # ### end Alembic commands ###
