"""init

Revision ID: b5eab8a8a954
Revises: 54ea7ee520e2
Create Date: 2020-10-22 10:10:14.289282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eab8a8a954'
down_revision = '54ea7ee520e2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
